import { atom, useAtom } from "jotai";
import { useRef, useState } from "react";
import { AvatarCreator } from "@readyplayerme/react-avatar-creator";
import { motion } from "framer-motion";

export const avatarUrlAtom = atom(
    localStorage.getItem("avatarURL") ||
    "https://models.readyplayer.me/64f0265b1db75f90dcfd9e2c.glb?meshlod=1&quality=medium"
);

export const AvatarCreateButton = () => {
  const [avatarMode, setAvatarMode] = useState(false);
  const [avatarUrl, setAvatarUrl] = useAtom(avatarUrlAtom);
  const ref = useRef(null);

  return (
      <>
        <motion.div
            ref={ref}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.5, delay: 0.5 }}
        >
          {avatarMode && (
              <AvatarCreator
                  subdomain="wawa-sensei-tutorial"
                  className="fixed top-0 left-0 z-[999999999] w-full h-full" // have to put a crazy z-index to be on top of HTML generated by Drei
                  onAvatarExported={(event) => {
                    let newAvatarUrl =
                        event.data.url === avatarUrl.split("?")[0]
                            ? event.data.url.split("?")[0] + "?" + new Date().getTime()
                            : event.data.url;
                    newAvatarUrl +=
                        (newAvatarUrl.includes("?") ? "&" : "?") +
                        "meshlod=1&quality=medium";
                    setAvatarUrl(newAvatarUrl);
                    localStorage.setItem("avatarURL", newAvatarUrl);
                    setAvatarMode(false);
                  }}
              />
          )}
          <div className="fixed inset-4 flex items-center justify-end flex-col pointer-events-none select-none">
            <div className="flex items-center space-x-4 pointer-events-auto">
              {/* AVATAR */}
                <button
                    className="p-4 rounded-full bg-slate-500 text-white drop-shadow-md cursor-pointer hover:bg-slate-800 transition-colors"
                    onClick={() => setAvatarMode(true)}
                >
                  <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      strokeWidth={1.5}
                      stroke="currentColor"
                      className="w-6 h-6"
                  >
                    <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z"
                    />
                  </svg>
                </button>
            </div>
          </div>
        </motion.div>
      </>
  );
};
